name: Those People
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92841
title: Those People
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e4d7ce'
    - '#92a0a0'
    - '#514d28'
    - '#8b7f4b'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
