name: Those People
favicon: null
layout_spectrum: 0.8874126102309674
typography_spectrum: 0.8352844340261072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3439449218567461
  lightness: 0.9225442896131426
  saturation: 0.5071955651510507
  rhythmicContrast: 0.08325954643078148
purpose: []
