name: Those People
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60328
title: Those People
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040509'
    - '#767772'
    - '#1a2129'
    - '#353e3d'
    - '#dd3e18'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
